### ISSUE TITLE
[BUG]: a bug "Sorry, something went wrong!" and <iframe> 

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#308] opened 2023-09-26 05:47 UTC
**Describe the bug**

Use <iframe> to play a youtube music video on md file1. At the same time, edit md file2. During editing, "Sorry, something went wrong!" pops up randomly.

**To Reproduce**
1. Open a md file and insert <iframe> to play a youtube video. 
2. Open another md file to input something.
3. "Sorry, something went wrong!" randomly pops up. And I need to restart the linebyline.
4. ChatGPT is also used at the same time. Not sure if this is connected to "Sorry, something went wrong!"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win 10
 - Version 0.5.3

**Additional context**

**Comment by drl990114** [comment] 2023-09-26 12:26
I don’t have a reproduction, can you provide the text?

**Comment by drl990114** [comment] 2023-09-27 15:21
Okay, thank you. I will consider optimizing the iframe part later and separate it into a separate node instead of processing it as an html block.

**Comment by yu2chuan** [comment] 2023-09-28 02:49
Supporting <iframe> is a great thing. Users can add some podcast, youtube video, and spotify music in the notes. Marktext can't do this.

**Comment by drl990114** [comment] 2023-10-01 12:30
This part will be considered in the future, because currently it is still based on commonmark, and HTML-related nodes will be optimized based on more user feedback in the future.

**Comment by yu2chuan** [comment] 2023-10-02 04:13
on 10/1, I met this message ,"Sorry, something went wrong" again. At that time, I opened only one md file and there was any <iframe> in the content. Now, I suspect it's related to "auto save". I will turn off "auto save" for a while to verify this.

**Comment by drl990114** [comment] 2023-10-02 10:34
Thanks for the feedback, I will also test it more on Windows to see if it can be reproduced.

**Comment by yu2chuan** [comment] 2023-12-09 09:28
on 0.6.2, the program crashes at times. I do believe it connected to auto save.
When enable the auto save and give a short intervals, create a table and edit it. it's an easy way to reprodruce this warning. It will not take long time.

**Comment by drl990114** [comment] 2023-12-10 10:30
I am still checking this part. If it appears frequently on your computer, then this may be more related to the Windows system, because I have not encountered this problem on the Mac system so far. I'll try to fix it in the next version

**Comment by drl990114** [comment] 2024-02-27 15:02
This bug should  be resolved in version 0.7.6.

**Closed by drl990114** 2024-02-27 15:02 UTC
Labels: bug
