### ISSUE TITLE
What's the plan for the ChatGPT

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#489] opened 2024-02-06 02:43 UTC
**Describe the bug**
ChatGPT can't work for a while. What's the plan for the ChatGPT feature? Will it change to the other AI engine such us Bing?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: [e.g. MacOS x86]
 - Version [e.g. 0.0.1]

**Additional context**

**Comment by drl990114** [comment] 2024-02-06 07:33
The issue of chatgpt will be included in the plan list and is expected to be supported in the next two versions, and MarkFlowy is expected to support a thin and light plug-in system to support other ai engines.

**Closed** 2024-04-13 17:36 UTC
Labels: enhancement

**Comment by yu2chuan** [comment] 2024-04-14 13:48
completed? wow. I can't wait.

**Comment by drl990114** [comment] 2024-04-14 15:29
Yes, it has been released. Currently, two functions have been added, summary and translation, and some small functions will be added in the future. However, the main goal in the short term is to supplement the editing experience and the basic functions of the application.

**Comment by yu2chuan** [comment] 2024-04-16 02:18
I used a new API key I just applied for yesterday. But I still received "request error, please check your ApiKey; is it right or not setting" on the version 0.8.0. Do you have any suggestions?

**Comment by drl990114** [comment] 2024-04-16 12:21
I have not reproduced this problem on `windows` and `macos`. You can try using `ctrl + a` to select and delete them all, and then copy them completely to make sure there are no extra characters.

**Comment by yu2chuan** [comment] 2024-04-18 04:07
I've tried. But it didn't work. I mean I still get a "request error, please check your ApiKey; is it right or not setting."

**Comment by drl990114** [comment] 2024-04-18 06:49
Have you tried switching gpt model? The default is `gpt-3.5-turbo`.

**Comment by siddique-abubakr** [comment] 2025-09-07 15:42
The issue mentioned by @yu2chuan is what I am facing too, no matter what I do, the message `request error, please check you ApiKey is it right or not`. If you need any more info from me to reopen the issue, I'll be happy to provide it. @drl990114

**Comment by drl990114** [comment] 2025-09-08 14:56
> The issue mentioned by [@yu2chuan](https://github.com/yu2chuan) is what I am facing too, no matter what I do, the message `request error, please check you ApiKey is it right or not`. If you need any more info from me to reopen the issue, I'll be happy to provide it. [@drl990114](https://github.com/drl990114)


I currently do not have a GPT key to test here. In the next version, I will optimize the error prompt and display the specific error content

**Comment by siddique-abubakr** [comment] 2025-09-09 09:20
> > The issue mentioned by [@yu2chuan](https://github.com/yu2chuan) is what I am facing too, no matter what I do, the message `request error, please check you ApiKey is it right or not`. If you need any more info from me to reopen the issue, I'll be happy to provide it. [@drl990114](https://github.com/drl990114)
> 
> I currently do not have a GPT key to test here. In the next version, I will optimize the error prompt and display the specific error content

Thanks, I'll take a look at it myself too. Since I do have an OpenAI key right now.

**Comment by drl990114** [comment] 2025-09-27 12:29
I know why. You can delete the default baseurl in setting. The next version will not use this.
